export const API_KEY = '&appid=902d167e0e5ec3836be796545b68317e';
export const FETCH_WEATHER_REQUESTS = 'FETCH_WEATHER_REQUESTS';
export const FETCH_WEATHER_ERR = 'FETCH_WEATHER_ERR';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';